#!/bin/bash
set -e

echo "Starting setup..." | tee /var/log/user-data.log

# Update system
yum update -y 2>&1 | tee -a /var/log/user-data.log

# Install Docker
amazon-linux-extras install docker -y 2>&1 | tee -a /var/log/user-data.log
systemctl start docker
systemctl enable docker
usermod -a -G docker ec2-user

# Install Docker Compose v2
DOCKER_COMPOSE_VERSION="v2.24.0"
curl -SL "https://github.com/docker/compose/releases/download/$${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose

# Install git
yum install -y git 2>&1 | tee -a /var/log/user-data.log

# Clone the repository if URL provided
%{ if repo_url != "" ~}
cd /home/ec2-user
git clone ${repo_url} app 2>&1 | tee -a /var/log/user-data.log || echo "Clone failed or repo already exists"
chown -R ec2-user:ec2-user /home/ec2-user/app

# Create .env file with Terraform-injected secrets
cat > /home/ec2-user/app/.env << 'ENVFILE'
# Auto-generated by Terraform
MYSQL_ROOT_PASSWORD=${db_root_password}
MYSQL_DATABASE=${db_name}
MYSQL_USER=${db_user}
MYSQL_PASSWORD=${db_password}

# Ports
FRONTEND_PORT=${frontend_port}
WEB_PORT=${backend_port}
DB_PORT=3306
ENVFILE

chown ec2-user:ec2-user /home/ec2-user/app/.env
chmod 600 /home/ec2-user/app/.env

%{ if auto_start ~}
# Auto-start the application using deploy script
echo "Starting application..." | tee -a /var/log/user-data.log
cd /home/ec2-user/app
sudo -u ec2-user bash scripts/deploy.sh up 2>&1 | tee -a /var/log/user-data.log
echo "Application started!" | tee -a /var/log/user-data.log
%{ endif ~}
%{ endif ~}

echo "Setup complete!" | tee /home/ec2-user/setup-complete.txt
echo "Docker version: $(docker --version)" >> /home/ec2-user/setup-complete.txt
echo "Docker Compose version: $(docker-compose --version)" >> /home/ec2-user/setup-complete.txt
%{ if auto_start ~}
echo "Application auto-started: YES" >> /home/ec2-user/setup-complete.txt
%{ else ~}
echo "Application auto-started: NO (run 'cd ~/app && bash scripts/deploy.sh up')" >> /home/ec2-user/setup-complete.txt
%{ endif ~}
